swagger: "2.0"

info:
  title: Annotation Suggestions API
  description: Provides suggestions for draft content.
  version: 0.0.0
  license:
    name: MIT
  contact:
    name: Universal Publishing
    email: universal.publishing@ft.com

host: api.ft.com
basePath: "/"
schemes:
  - http
  - https

paths:
  /__health:
    get:
      summary: Healthchecks
      description: Runs application healthchecks and returns FT Healthcheck style json.
      produces:
        - application/json
      tags:
        - Health
      responses:
        200:
          description: >
            Should always return 200 along with the output of the healthchecks - regardless
            of whether the healthchecks failed or not.
            Please inspect the overall ok property to see whether or not the application is healthy.
          examples:
            application/json:
              schemaVersion: 1
              systemCode: draft-content-api
              name: draft-content-api
              description: A descriptive description
              checks:
                - id: check-content-api-health
                  name: Check Content API Health
                  ok: false
                  severity: 1
                  businessImpact: Impossible to serve content through PAC
                  technicalSummary: Content API is not available at http://test.api.ft.com/content
                  panicGuide: https://runbooks.ftops.tech/draft-content-api
                  checkOutput: gtg returned a non-200 HTTP status
                  lastUpdated: 2017-08-03T10:44:32.324709638+01:00
              ok: true
  /__gtg:
    get:
      summary: Good To Go
      description: Lightly healthchecks the application, and returns a 200 if it's Good-To-Go.
      tags:
        - Health
      produces:
          - text/plain; charset=US-ASCII
      responses:
        200:
          description: The application is healthy enough to perform all its functions correctly - i.e. good to go.
          examples:
               text/plain; charset=US-ASCII: OK
        503:
          description: >
            One or more of the applications healthchecks have failed,
            so please do not use the app. See the /__health endpoint for more detailed information.
  /__build-info:
    get:
      summary: Build Information
      description: >
        Returns application build info, such as the git repository and revision,
        the golang version it was built with, and the app release version.
      produces:
        - application/json; charset=UTF-8
      tags:
        - Info
      responses:
        200:
          description: Outputs build information as described in the summary.
          examples:
            application/json; charset=UTF-8:
              version: 0.0.1
              repository: https://github.com/Financial-Times/draft-content-suggestions.git
              revision: 7cdbdb18b4a518eef3ebb1b545fc124612f9d7cd
              builder: go version go1.8.3 linux/amd64
              dateTime: "20161123122615"
  /drafts/content/{uuid}/suggestions:
    get:
      summary: Get Draft Content Suggestions
      description: >
        Fetches the draft content with the provided uuid from draft-content-api and returns suggestions via
        using suggestions umbrella service.
      produces:
        - application/json
      tags:
        - Public API
      parameters:
        - name: uuid
          in: path
          description: The UUID of the content
          required: true
          type: string
          x-example: 97c97db4-4a93-43a4-87c9-b04d7f5284c1
      responses:
        200:
          description: Suggestions Response
          schema:
            type: object
            properties:
              suggestions:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The canonical ID of the concept
                      x-example: http://www.ft.com/thing/d7113d1d-ed66-3adf-9910-1f62b2c40e6a
                    predicate:
                      type: string
                      description: The relationship between the concept and this piece of FT content. The list below is non-exhaustive and subject to change.
                      enum:
                        - http://www.ft.com/ontology/annotation/about
                        - http://www.ft.com/ontology/implicitlyAbout
                        - http://www.ft.com/ontology/annotation/mentions
                        - http://www.ft.com/ontology/classification/isClassifiedBy
                        - http://www.ft.com/ontology/implicitlyClassifiedBy
                        - http://www.ft.com/ontology/hasContributor
                    type:
                      type: string
                      description: The type of concept, i.e. Person, Organisation, Topic
                    apiUrl:
                      type: string
                      description: The FT API url of the concept
                      x-example: http://api.ft.com/things/5507ab98-b747-3ebc-b816-11603b9009f4
                    prefLabel:
                      type: string
                      description: The preferred display label for the concept.
                    isFTAuthor:
                      type: boolean
                      description: Is this person an FT author or not. Only applies to concepts of type People.
                  required:
                    - id
                    - predicate
            required:
              - suggestions
          examples:
            application/json:
              suggestions:
                - apiUrl: http://api.ft.com/people/6f14ea94-690f-3ed4-98c7-b926683c735a
                  id: http://www.ft.com/thing/6f14ea94-690f-3ed4-98c7-b926683c735a
                  isFTAuthor: false
                  predicate: http://www.ft.com/ontology/annotation/about
                  prefLabel: Donald Kaberuka
                  type: http://www.ft.com/ontology/person/Person
                - apiUrl: http://api.ft.com/people/9a5e3b4a-55da-498c-816f-9c534e1392bd
                  id: http://www.ft.com/thing/9a5e3b4a-55da-498c-816f-9c534e1392bd
                  isFTAuthor: true
                  predicate: http://www.ft.com/ontology/annotation/mentions
                  prefLabel: Lawrence Summers
                  type: http://www.ft.com/ontology/person/Person
