apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && PathPrefix(`/__{{ .Values.service.name }}/`)
      middlewares:
      - name: basic-auth
        namespace: default
      - name: replace-path-{{ .Values.service.name }}
        namespace: default
      services:
      - kind: Service
        namespace: default
        name: {{ .Values.service.name }}
        port: 8080
        passHostHeader: true
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && PathPrefix(`/drafts/content/{.*}/suggestions`)
      priority: 5
      middlewares:
      - name: basic-auth
        namespace: default
      services:
      - kind: Service
        name: {{ .Values.service.name }}
        namespace: default
        passHostHeader: true
        port: 8080
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && PathPrefix(`/drafts/content/suggestions`)
      priority: 5
      middlewares:
      - name: basic-auth
        namespace: default
      services:
      - kind: Service
        name: {{ .Values.service.name }}
        namespace: default
        passHostHeader: true
        port: 8080
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
